/** @libar-docs */

// TODO: Minimum annotation and minimum information! Only linking deliverables to phases.
// If we need more detail here that should be generated by the delivery process.

/**
 * @libar-docs-arch @libar-docs-core
 * @libar-docs-pattern FoundationInfrastructure
 * @libar-docs-phase 1
 * @libar-docs-status completed
 * @libar-docs-quarter Q4-2025
 * @libar-docs-completed 2025-12-31
 * @libar-docs-effort 12w
 * @libar-docs-product-area Platform
 * @libar-docs-enables EventStore, CommandBus, CommandOrchestrator
 *
 * ## Phase 1: Foundation Infrastructure
 *
 * Consolidates old roadmap phases 0-13 into a single completed milestone.
 *
 * ### Included Components
 *
 * | Component | Package | Description |
 * |-----------|---------|-------------|
 * | Event Store | platform-store | Central event storage with OCC |
 * | Command Bus | platform-bus | Command idempotency infrastructure |
 * | CMS Patterns | platform-core | Command Model State dual-write |
 * | Projections | platform-core | Checkpoint-based read model updates |
 * | Correlation | platform-core | Request tracing via correlation chains |
 * | EventBus | platform-core | Publish/subscribe event delivery |
 * | Middleware | platform-core | Command pipeline with hooks |
 * | Invariants | platform-core | Domain rule enforcement |
 *
 * ### Key Patterns Established
 *
 * - **Dual-Write Pattern**: CMS update + event append atomic
 * - **Component Isolation**: Physical bounded context boundaries
 * - **Optimistic Concurrency**: Version-based conflict detection
 * - **Workpool-Based Projections**: Durable, ordered processing
 *
 * Reference: docs/project-management/roadmap/ (old phases 0-13)
 */
export interface Phase01FoundationInfrastructure {
  readonly phase: 1;
  readonly release: "v0.1.0";
}
